version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
  web-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web-tests
    volumes:
      - /app/node_modules
      - ./:/app
    command: ["npm","run","test"]