name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t saitejagoudkasala/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true saitejagoudkasala/docker-react npm test
